/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bol26;

import java.util.ArrayList;

/**
 *
 * @author dsoutofernandez
 */
public class Boleto extends javax.swing.JFrame {

    ArrayList numeros = new ArrayList<String>(6);
    int Numnum = 0;
    
    /**
     * Creates new form Boleto
     */
    public Boleto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel50 = new javax.swing.JLabel();
        Numero1 = new javax.swing.JLabel();
        Numero2 = new javax.swing.JLabel();
        Numero3 = new javax.swing.JLabel();
        Numero4 = new javax.swing.JLabel();
        Numero5 = new javax.swing.JLabel();
        Numero6 = new javax.swing.JLabel();
        console = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel51 = new javax.swing.JLabel();
        Numero7 = new javax.swing.JLabel();
        Numero8 = new javax.swing.JLabel();
        Numero9 = new javax.swing.JLabel();
        Numero10 = new javax.swing.JLabel();
        Numero11 = new javax.swing.JLabel();
        Numero12 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        ConsolaPremio = new javax.swing.JLabel();
        BotonC = new javax.swing.JButton();
        jLabel52 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setText("2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setText("3");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setText("4");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setText("5");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setText("6");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setText("7");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setText("8");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setText("9");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setText("10");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel11.setText("11");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel12.setText("12");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel13.setText("13");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel14.setText("14");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jLabel15.setText("15");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        jLabel16.setText("16");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jLabel17.setText("17");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        jLabel18.setText("18");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        jLabel19.setText("19");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        jLabel20.setText("20");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });

        jLabel21.setText("21");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });

        jLabel22.setText("22");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        jLabel23.setText("23");
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });

        jLabel24.setText("24");
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });

        jLabel25.setText("25");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });

        jLabel26.setText("26");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });

        jLabel27.setText("27");
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });

        jLabel28.setText("28");
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });

        jLabel29.setText("29");
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });

        jLabel30.setText("30");
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });

        jLabel31.setText("31");
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });

        jLabel32.setText("32");
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });

        jLabel33.setText("33");
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });

        jLabel34.setText("34");
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });

        jLabel35.setText("35");
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
        });

        jLabel36.setText("36");
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });

        jLabel37.setText("37");
        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel37MouseClicked(evt);
            }
        });

        jLabel38.setText("38");
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });

        jLabel39.setText("39");
        jLabel39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel39MouseClicked(evt);
            }
        });

        jLabel40.setText("40");
        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel40MouseClicked(evt);
            }
        });

        jLabel41.setText("41");
        jLabel41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel41MouseClicked(evt);
            }
        });

        jLabel42.setText("42");
        jLabel42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel42MouseClicked(evt);
            }
        });

        jLabel43.setText("43");
        jLabel43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel43MouseClicked(evt);
            }
        });

        jLabel44.setText("44");
        jLabel44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel44MouseClicked(evt);
            }
        });

        jLabel45.setText("45");
        jLabel45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel45MouseClicked(evt);
            }
        });

        jLabel46.setText("46");
        jLabel46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel46MouseClicked(evt);
            }
        });

        jLabel47.setText("47");
        jLabel47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel47MouseClicked(evt);
            }
        });

        jLabel48.setText("48");
        jLabel48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel48MouseClicked(evt);
            }
        });

        jLabel49.setText("49");
        jLabel49.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel49MouseClicked(evt);
            }
        });

        jLabel50.setText("Tus numeros son:");

        jLabel51.setText("Los numeros premiados son:");

        BotonC.setText("Comprobar Premio");
        BotonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCActionPerformed(evt);
            }
        });

        jLabel52.setIcon(new javax.swing.ImageIcon("/home/local/DANIELCASTELAO/dsoutofernandez/MEGA/NetBeansProjects/Boletines/Boletin 26/Castelao.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(BotonC)
                        .addContainerGap(117, Short.MAX_VALUE))
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ConsolaPremio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Numero7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Numero8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Numero9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Numero10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Numero11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Numero12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel44, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel46, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel47, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel48, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel49, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(console, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel50)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Numero2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Numero3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Numero4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Numero5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Numero6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel51)
                            .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jLabel44)
                    .addComponent(jLabel45)
                    .addComponent(jLabel46)
                    .addComponent(jLabel47)
                    .addComponent(jLabel48)
                    .addComponent(jLabel49))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(console, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel50)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Numero2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Numero3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(Numero5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Numero6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Numero4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Numero7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numero8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numero9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numero10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numero11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numero12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConsolaPremio, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonC)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
            
        this.jLabel1.setText("");
        numeros.add("1");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
        
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel2.setText("");
        numeros.add("2");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        
        this.jLabel3.setText("");
        numeros.add("3");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel4.setText("");
        numeros.add("4");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
          this.jLabel5.setText("");
        numeros.add("5");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
          this.jLabel6.setText("");
        numeros.add("6");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
        
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
          this.jLabel7.setText("");
        numeros.add("7");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
          this.jLabel8.setText("");
        numeros.add("8");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
          this.jLabel9.setText("");
        numeros.add("9");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
          this.jLabel10.setText("");
        numeros.add("10");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
          this.jLabel11.setText("");
        numeros.add("11");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
        
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
          this.jLabel12.setText("");
        numeros.add("12");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
          this.jLabel13.setText("");
        numeros.add("13");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
          this.jLabel14.setText("");
        numeros.add("14");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
          this.jLabel15.setText("");
        numeros.add("15");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
          this.jLabel16.setText("");
        numeros.add("16");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
          this.jLabel17.setText("");
        numeros.add("17");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
          this.jLabel18.setText("");
        numeros.add("18");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
          this.jLabel19.setText("");
        numeros.add("19");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
          this.jLabel20.setText("");
        numeros.add("20");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel21.setText("");
        numeros.add("21");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel22.setText("");
        numeros.add("22");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel23.setText("");
        numeros.add("23");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel24.setText("");
        numeros.add("24");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel25.setText("");
        numeros.add("25");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel26.setText("");
        numeros.add("26");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel27.setText("");
        numeros.add("27");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel28.setText("");
        numeros.add("28");if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel29.setText("");
        numeros.add("29");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel30.setText("");
        numeros.add("30");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel31.setText("");
        numeros.add("31");if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel32.setText("");
        numeros.add("32");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel33.setText("");
        numeros.add("33");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel34.setText("");
        numeros.add("34");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel35.setText("");
        numeros.add("35");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel35MouseClicked

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel36.setText("");
        numeros.add("36");if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel36MouseClicked

    private void jLabel37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel37.setText("");
        numeros.add("37");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel37MouseClicked

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel38.setText("");
        numeros.add("38");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel38MouseClicked

    private void jLabel39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel39MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel39.setText("");
        numeros.add("39");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel39MouseClicked

    private void jLabel40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel40.setText("");
        numeros.add("40");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel40MouseClicked

    private void jLabel41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel41MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel41.setText("");
        numeros.add("41");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel41MouseClicked

    private void jLabel42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel42MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel42.setText("");
        numeros.add("42");if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel42MouseClicked

    private void jLabel43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel43MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel43.setText("");
        numeros.add("43");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel43MouseClicked

    private void jLabel44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel44.setText("");
        numeros.add("44");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel44MouseClicked

    private void jLabel45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel45MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel45.setText("");
        numeros.add("45");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel45MouseClicked

    private void jLabel46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel46MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel46.setText("");
        numeros.add("46");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel46MouseClicked

    private void jLabel47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel47MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel47.setText("");
        numeros.add("47");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel47MouseClicked

    private void jLabel48MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel48MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel48.setText("");
        numeros.add("48");if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel48MouseClicked

    private void jLabel49MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel49MouseClicked
        // TODO add your handling code here:
        if(Numnum<6){
        this.jLabel49.setText("");
        numeros.add("49");
        if(Numnum==0){
        this.Numero1.setText(numeros.get(Numnum).toString());
        }else if(Numnum==1){
        this.Numero2.setText(numeros.get(Numnum).toString());
        }else if(Numnum==2){
        this.Numero3.setText(numeros.get(Numnum).toString());
        }else if(Numnum==3){
        this.Numero4.setText(numeros.get(Numnum).toString());
        }else if(Numnum==4){
        this.Numero5.setText(numeros.get(Numnum).toString());
        }else if(Numnum==5){
        this.Numero6.setText(numeros.get(Numnum).toString());
        }
        Numnum = Numnum+1;
        }else{this.console.setText("Ya tiene 6 numeros");}
    }//GEN-LAST:event_jLabel49MouseClicked

    private void BotonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCActionPerformed
        // TODO add your handling code here:
        
        
        ArrayList numPrem = new ArrayList<String>();
        int aciertos = 0;
        
        do{
        
          boolean repetido= false; 
            
        int num=(int)(Math.random()*49);
        
            for (int i = 0; i < numPrem.size(); i++) {
                
                if (Integer.parseInt(numPrem.get(i).toString()) == num || num ==0){
                
                    repetido = true;
                
                }
                
            }
        
            if (repetido == false){
            
                numPrem.add(num);
                
            }
        
        }while(numPrem.size()<6);
        
        
        this.Numero7.setText(numPrem.get(0).toString());
        this.Numero8.setText(numPrem.get(1).toString());
        this.Numero9.setText(numPrem.get(2).toString());
        this.Numero10.setText(numPrem.get(3).toString());
        this.Numero11.setText(numPrem.get(4).toString());
        this.Numero12.setText(numPrem.get(5).toString());
        
        
        for (int i = 0; i < numeros.size(); i++) {
            
            for (int j = 0; j < numPrem.size(); j++) {
                
                if (numeros.get(i).toString().equals(numPrem.get(j).toString())){
                
                    aciertos = aciertos +1;
                    
                }
                
                
            }
            
            
        }
        
        this.ConsolaPremio.setText("Ha tenido "+aciertos+ " aciertos");
        
        
        
    }//GEN-LAST:event_BotonCActionPerformed

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Boleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Boleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Boleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Boleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Boleto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonC;
    private javax.swing.JLabel ConsolaPremio;
    private javax.swing.JLabel Numero1;
    private javax.swing.JLabel Numero10;
    private javax.swing.JLabel Numero11;
    private javax.swing.JLabel Numero12;
    private javax.swing.JLabel Numero2;
    private javax.swing.JLabel Numero3;
    private javax.swing.JLabel Numero4;
    private javax.swing.JLabel Numero5;
    private javax.swing.JLabel Numero6;
    private javax.swing.JLabel Numero7;
    private javax.swing.JLabel Numero8;
    private javax.swing.JLabel Numero9;
    private javax.swing.JLabel console;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
